spring:
  application:
    name: mqtt-messager
  cloud:
    nacos:
      discovery:
        server-addr: guizhou:8848
dubbo:
  application:
    name: mqtt-messager
  #协议配置端口
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: nacos://guizhou:8848
    
server:
  port: 8989

#mqtt properties
mqtt:
  uris:
    - tcp://guizhou:1883
  clientId: mqtt_test
  topics:
    - demo
    - test
    - v2/action/command
    - v2/+/response
  username: admin
  password: public
  timeout: 30
  keepalive: 60
  qos: 1
