spring:
  application:
    name: MQTT-DEMO
server:
  port: 8989

#mqtt properties
mqtt:
  uris:
    - tcp://127.0.0.1:1883
  clientId: mqtt_test1
  topics:
    - demo
    - test
  username: admin
  password: 123456
  timeout: 30
  keepalive: 60
  qos: 1
